### ISSUE TITLE
Roadmap to add more features?

### ISSUE THREAD

**Issue by spacewander** [mosn/envoy-go-extension#48]
Currently, this extension already supports:
- [x] process HTTP request
- [x] send local response
- [x] get HTTP request headers
- [x] modify HTTP request headers
- [x] get HTTP request body
- [x] set HTTP request body
- [x] process HTTP response
- [x] get HTTP response headers
- [x] modify HTTP response headers
- [x] get all / set HTTP trailers
- [x] get HTTP response body
- [x] set HTTP response body

According to the proxy wasm spec, more features can be implemented. For example:
* run Go when Envoy starts as a bootstrap extension
* get/set Envoy property
* interact with Go filters run in different workers via the shared data/queue
* define/record metric

Will there be a plan to implement those features?

**Comment by doujiang24** [comment]
> run Go when Envoy starts as a bootstrap extension

This could be useful, but we are pushing this extension into envoy official repo: https://github.com/envoyproxy/envoy/pull/22573
(BTW, the new changes will also push envoy, after it is merged)
There is no bootstrap extension, according to Matt's requirement.

So, it may be delayed.

> interact with Go filters run in different workers via the shared data/queue

I have no idea about the shared data/queue. could you help to give some points for refers?

> get/set Envoy property
> define/record metric

Yeah, these are planned, PRs welcome.

But, not a full detailed todo list yet.

**Comment by spacewander** [comment]
> I have no idea about the shared data/queue. could you help to give some points for refers?

I think about it again. We don't need it because unlike the Wasm filter, the data in Go filter is already shared between worker threads.
